### PR TITLE
Map: show simple dot as marker on path

### PR DESCRIPTION
**Pull request by lukarenko**
Suggestion to use simple marker instead of sailboat which clutters the image

Before:
image

After:
image

### CODE REVIEW

**Comment by xbgmsharp** [comment]
Technically, It is suppose to be a sailboat or a motorboat icon, could more options. Agreed there is too many point display, for long logs. I was thinking to display one out of two.

**Comment by lukarenko** [comment]
But it does not make sense to have multiple boats shown on the same track, it is kind of misleading. Also you want indicators where you can get the popup with more data. 

I would add sailboat/powerboat in timelapse on current position. Also, we could add different sailboat sail setup for apparent wind angle: close-hauled, beam reach, broad reach, run
https://www.kavas.com/media/wysiwyg/sail_chC1.jpg

When you select particular point on the track, we could overlay the sailboat with sail setup. I think that would be cool.

I think we should/could get all the data for the track points:
- course over ground 
- speed over ground
- apparent wind angle and speed
- true wind direction
- true wind speed

**Comment by xbgmsharp** [comment]
Sorry i am confused, it should display either a sailboat or a motorboat not both as it does not make sense.
Currently, the following data is present in the geojson. More can be add.
```
      "properties": {
        "time": "",
        "notes": "",
        "latitude": ,
        "longitude": ,
        "speedoverground": ,
        "windspeedapparent": ,
        "courseovergroundtrue": 
      }
```

**Comment by lukarenko** [comment]
I agree, displaying sailboat or powerboat on track does not make sense if sailing/motoring. As I already said, I would display only one boat at a time on the map - only on current location (like in timelapse), but not on each track point. I would use then different color for sailing (let say green) than motoring (let say blue) for the track between points.

Regarding geojson: it would be great if we could add these three fields:
- true wind direction (TWD)
- true wind speed (TWS)
- mode (sailing/motoring)

That way, we could:

1. show sailboat on the current position with sail configuration:
  - no sails - motoring
  - close-hauled (when abs(TWD - COG) is 0 to 50 degrees)
  - close reach (when abs(TWD - COG) is  50-80
  - beam reach (when abs(TWD - COG) is  80-110
  - broad reach (when TWD - COG is 110-150
  - run - sails on oposite sides (when abs(TWD - COG) is 150-180
https://asa.com/wordpress/wp-content/uploads/2019/02/News-2019-02-11-Points-of-Sail-961x1024.jpg
  
2. show wind arrow and direction in corner/legend of the map 
  - maybe best shown with wind barbs
  - or just direction triangle + windspeed in kts
https://michigan-weather-center.org/wp-content/uploads/2019/02/windbarbs.jpg

**Comment by xbgmsharp** [comment]
I like the concept of the dot on map instead of a sailboat or motorboat. However it should be an option in the preference.
Let discuss on how we can improve. In the meantime will close this as it conflict the latest change on the map

**Pull request closed without merging**
